services:
  gateway:
    image: nginx
    restart: always
    networks:
      - main
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  user:
    build: ./user
    networks:
      - main
    environment:
      HOST: database
      USERNAME: postgres
      PASSWORD: postgres
      DATABASE: postgres

  products:
    build: ./products
    networks:
      - main
    environment:
      HOST: database
      USERNAME: postgres
      PASSWORD: postgres
      DATABASE: postgres

  orders:
    build: ./orders
    networks:
      - main
    environment:
      HOST: database
      USERNAME: postgres
      PASSWORD: postgres
      DATABASE: postgres

  database:
    image: postgres
    restart: always
    shm_size: 128mb
    networks:
      - main
    environment:
      POSTGRES_PASSWORD: postgres

networks:
  main:
    driver: bridge
