services:
  user:
    ports:
      - 3000:3000
    build: ./user
    environment:
      HOST: database
      USERNAME: postgres
      PASSWORD: postgres
      DATABASE: postgres

  orders:
    ports:
      - 3100:3100
    build: ./orders
    environment:
      HOST: database
      USERNAME: postgres
      PASSWORD: postgres
      DATABASE: postgres

  products:
    ports:
      - 3200:3200
    build: ./products
    environment:
      HOST: database
      USERNAME: postgres
      PASSWORD: postgres
      DATABASE: postgres

  database:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
